stages:
 - test

variables:
  CURRENT: 2021

##
## PHP
##
.composer:
  allow_failure: true
  image: php:7.3-cli
  stage: test
  before_script:
    - bash ${CI_PROJECT_DIR}/.ci/php/install_composer.sh
    - cd $YEAR/php
    - composer install -d ./src --no-progress --prefer-dist
  script:
    - php ./cli.php run

2018:php:
  extends: .composer
  variables:
    YEAR: 2018
  script:
    - php ./run.php

2019:php:
  extends: .composer
  image: php:7.4-cli
  variables:
    YEAR: 2019

2020:php:
  extends: .composer
  image: php:8.0-cli
  variables:
    YEAR: 2020

##
## Rust
##
.rust:
  stage: test
  image: rust:1.48
  before_script:
    - cd $YEAR/rust
  script:
    - ./build-all
    - ./run-all

2019:rust:
  extends: .rust
  variables:
    YEAR: 2019

##
## Julia
##
.julia:
  stage: test
  image: julia:1.5-alpine
  before_script:
    - cd $YEAR/julia/test
  script:
    - julia/test.jl

2019:julia:
  extends: .julia
  variables:
    YEAR: 2019

2020:julia:
  extends: .julia
  image: julia:1.6-alpine
  variables:
    YEAR: 2020

2021:julia:
  extends: .julia
  image: julia:1.7-alpine
  variables:
    YEAR: 2021

##
## Typescript
##
.typescript:
  stage: test
  image: node:latest
  variables:
    YEAR: 2021
  before_script:
    - cd lib/typescript/aoc
    - yarn install
    - cd $CI_PROJECT_DIR
  script:
    - cd $YEAR/typescript/src
    - yarn install
    - yarn run aoc
  rules:
    - if:
      changes:
         - $YEAR/typescript/src/days/*
      when: on_success
    - if: $YEAR != $CURRENT
      when: manual

2020:typescript:
  extends: .typescript
  variables:
    YEAR: 2020

2021:typescript:
  extends: .typescript
  variables:
    YEAR: 2021
