stages:
 - test

test-2018-php7.2:
  stage: test
  image: php:7.2-cli
  before_script:
    - cd 2018/php
    - ./ci/install_composer.sh
    - composer install
  script:
    - php ./run.php

test-2018-php7.3:
  stage: test
  image: php:7.3-cli
  before_script:
    - cd 2018/php
    - ./ci/install_composer.sh
    - composer install
  script:
    - php ./run.php
