stages:
 - test

.composer:
  before_script:
    - bash ${CI_PROJECT_DIR}/.ci/php/install_composer.sh

test:2018:php7.3:
  extends: .composer
  stage: test
  image: php:7.3-cli
  only:
    changes:
     - 2018/php/**
  script:
    - cd 2018/php
    - composer install
    - php ./run.php

test:2019:php7.4:
  extends: .composer
  stage: test
  image: php:7.4-cli
  only:
    changes:
     - 2019/php/**
  script:
    - cd 2019/php
    - composer install -d ./src --no-progress --prefer-dist
    - php ./cli.php run

test:2019:rust1.48:
  stage: test
  image: rust:1.48
  only:
    changes:
     - 2019/rust/**
  script:
    - cd 2019/rust
    - ./build-all
    - ./run-all

test:2019:julia1.5:
  stage: test
  image: julia:1.5-alpine
  only:
    changes:
     - 2019/julia/**
  script:
   - cd 2019/julia/test
   - julia test.jl

test:2020:php:
  extends: .composer
  allow_failure: true
  only:
    changes:
      - 2020/php/**
  parallel:
    matrix:
      - IMAGE:
        - php:7.4-cli
        - php:8.0-cli
  stage: test
  image: $IMAGE
  script:
    - cd 2020/php
    - composer install -d ./src --no-progress --prefer-dist
    - php ./cli.php run

test:2020:julia1.5:
  stage: test
  image: julia:1.5-alpine
  only:
    changes:
      - 2020/julia/**
  script:
   - cd 2020/julia/test
   - julia test.jl

.typescript:
  stage: test
  image: node:latest
  before_script:
    - cd lib/typescript/aoc
    - yarn install
    - cd $CI_PROJECT_DIR

test:2020:typescript:
  extends: .typescript
  only:
    changes:
      - 2020/typescript/**
  script:
    - cd 2020/typescript/src
    - yarn install
    - yarn run aoc

test:2021:typescript:
  extends: .typescript
  script:
    - cd 2021/typescript/src
    - yarn install
    - yarn run aoc

test:2021:julia:
  stage: test
  image: julia:1.7-alpine
  script:
    - cd 2021/julia/test
    - julia test.jl
