#!/bin/bash
docker run --rm \
            --volume=$(realpath .):/opt/advent/php \
            --volume=$(realpath ../input):/opt/advent/input \
            --volume=$(realpath ../expected):/opt/advent/expected \
            -w /opt/advent/php \
            -ti \
            php:7-cli \
            php "$@"
echo ""